Repository hannemariavister/terraform-nomad-nifiregistry, pull requests merged in 2021-02, with the labels that each got.

#49 Improve GitHub actions to run `make test-standalone`
  .github/workflows/on_pr_push_master.yml
  CHANGELOG.md
Labels: enhancement

#51 Issue 47 add description of `vault_secret`in the README section input
  CHANGELOG.md
  README.md
Labels: documentation

#53 Release 0.3.1
  CHANGELOG.md
Labels: patch
