Repository hannemariavister/terraform-nomad-nifiregistry, pull requests merged in 2021-01, with the labels that each got.

#18 update vagrant box
  CHANGELOG.md
  Vagrantfile
Labels: enhancement

#25 Issue 21 Add the option to choose between standalone example or standalone with git
  CHANGELOG.md
  Makefile
  README.md
  dev/ansible/01_run_terraform.yml
  example/standalone/main.tf
  main.tf
  variables.tf
Labels: enhancement

#27 Add an example `standalone_git` with a NiFi Registry container integrated with GIT version control
  .gitignore
  CHANGELOG.md
  Makefile
  README.md
  example/resources/images/nifi_registry_git_integration.png
  example/standalone_git/README.md
  example/standalone_git/main.tf
  example/standalone_git/providers.tf
  example/standalone_git/variables.tf
  main.tf
  nomad/nifi_registry_git_integration.hcl
  variables.tf
Labels: enhancement

#29 New release 0.2.0
  CHANGELOG.md
Labels: minor

#31 Issue 22 add readme to standalone
  CHANGELOG.md
  example/README.md
  example/resources/images/nifi_registry_standalone.png
  example/standalone/README.md
  example/standalone/main.tf
Labels: bug

#37 new release 0.2.1
  CHANGELOG.md
Labels: patch

#42 Secrets Management in Vault and variables in Consul Key Value Store
  .github/workflows/on_pr_push_master.yml
  CHANGELOG.md
  Makefile
  README.md
  dev/.env
  dev/ansible/01_put_secrets_vault.yml
  dev/ansible/02_put_variables_consul.yml
  dev/ansible/03_run_terraform.yml
  dev/vagrant/bootstrap/vault/post/01-create_vault_policy_to_read_secrets.yml
  example/standalone_git/README.md
  example/standalone_git/main.tf
  main.tf
  nomad/nifi_registry_git_integration.hcl
  variables.tf
Labels: enhancement, priority/high

#44 Let Ansible playbooks (file 01 and 02) only be executed for `example/standalone_git`
  CHANGELOG.md
  dev/ansible/01_put_secrets_vault.yml
  dev/ansible/02_put_variables_consul.yml
Labels: bug, priority/high

#46 Release 0.3.0
  CHANGELOG.md
Labels: minor
